apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::038963921844:role/UdacityFlaskDeployCBKubectlRole
      username: build   
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::038963921844:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1VIFHNHQQRTNF
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-12T21:21:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1424"
  uid: b28a6fd4-ea1a-42bd-a4c0-ebb6d94590c1
